# Generated by Django 4.2.3 on 2023-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('assignedto', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
